# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1676a79936c245d6a629e55ba4a2203424d3675d26a8acc5c54b99de78ff4b75e34871d0cd0d81a723840d6e27e1cb2121927d354c0bf3b5dce5ccf147bf146d

test:
  secret_key_base: c34c6a51a51184b5233e48dc2a13c9bf81d3ead899209d9efa38f82daaac8225a227ad6695590bb01bb075c33f991be03d1bf6625adfad9238338b29fd8b992e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
